launch: #起動パラメータ
  ros__parameters:
    joy: true
    livox_mid360: true
    odom: true

/**:  #ワイルドカード(ここのパラメータは全ノードから読める: <名前に注意>)
  ros__parameters:
    # 並進  速度[m/s],加速度[m/s^2],加減速度[-m/s^2],躍度[m/s^3]
    linear_max:
      vel : 1.8 #1.8
    # 回転  速度[deg/s],加速度[deg/s^2],加減速度[-deg/s^2],躍度[deg/s^3]
    angular_max :
      vel: 80.0 #80.0
    autonomous_flag : false

socketcan_interface_node:
  ros__parameters:
    if_name : "0"

chassis_driver_node:
  ros__parameters:
    wheel_radius : 0.03
    attached_direction : 0.200343
    stop_canid : 0x100
    restart_canid : 0x101
    motor_rev_canid : 0x102
    encoder_rev_canid : 0x103
    pidgain_canid : 0x104
    velocity_canid : 0x108

    motor_rev: [0, 1, 0, 0]
    encoder_rev: [0, 0, 0, 0]

    pidgain0: [1.0, 0.0, 0.01]
    pidgain1: [1.0, 0.0, 0.01]
    pidgain2: [1.0, 0.0, 0.01]
    pidgain3: [1.0, 0.0, 0.01]

pose_pid_node:
  ros__parameters:
    interval_ms : 10
    linear_pidgain : [2.0, 0.01, 0.0]
    # linear_pidgain : [1.1, 0.01, 0.0]
    angular_pidgain : [1.0, 0.01, 0.0]
    allowed_area : [-1.0, 1.0, -0.8, 0.8]   #[x下限，x上限，y下限，y上限]

qwiic_pose_node:
  ros__parameters:
    attached_pose : [0.0, 0.03, 0.0]    #x, y, yaw

cybergear_interface_node:
  ros__parameters:
    interval_ms : 10
    master_id : 0x00
    target_id : 0x7F

    gear_rate : 1.0
    reverse_flag : false
    # 制御対象の最小・最大位置[deg]
    pos_limit_min : -120.0
    pos_limit_max : -40.0
    # 制御対象の最大速度[deg/s] <-サイバーギアの限界速度以下に設定する
    limit_speed : 720.0 # 540

    # ゲイン
    pos_kp : 30.0

landmark_localization:
  ros__parameters:
    min_x: -1.0
    max_x: 1.0
    min_y: -1.5
    max_y: 1.5
    min_z: -0.3
    max_z: 1.1
    livox_pitch: 0.0
    landmark_width: 1.2
    landmark_height: 0.8
    width_tolerance: 0.1
    height_tolerance: 0.4
    laser_weight: 10.0
    odom_weight_liner: 1.0e-2
    odom_weight_angler: 1.0e-2
    plane_iterations: 30
    line_iterations: 30
    odom2laser_x: 0.165
    odom2laser_y: 0.02
    use_y_median: true

ball_detector:
  ros__parameters:
    min_x: 0.0
    max_x: 4.0
    min_y: -1.0
    max_y: 1.0
    min_z: 0.4
    max_z: 2.4
    livox_pitch: -16.0
    voxel_size_x: 0.15
    voxel_size_y: 0.15
    voxel_size_z: 0.15
    voxel_search_range: 1
    ball_radius: 0.15
    ball_vel_min: 0.00
    max_distance_for_association: 0.5
    missing_count_threshold: 15
    odom2laser_x: 0.165
    odom2laser_y: 0.02

impact_point_estimator:
  ros__parameters:
    motor_pos: 0.0
    reroad: -3.0
    offset_time: -0.04
    curve_points_num: 2
    standby_pose_x: 0.0
    standby_pose_y: 0.0
    lidar_to_target_x: 0.2
    lidar_to_target_y: 0.02
    lidar_to_target_z: 0.7
    V_min: 1.0
    V_max: 7.0
    expected_direction: [-1.0, 0.0, 0.0]
    theta_max_deg: 60.0
    first_goal_x: 0.0
    standby_delay: 1.0
