launch: #起動パラメータ
  ros__parameters:
    joy: true
    tracking_module: false

/**:  #ワイルドカード(ここのパラメータは全ノードから読める: <名前に注意>)
  ros__parameters:
    # 並進  速度[m/s],加速度[m/s^2],加減速度[-m/s^2],躍度[m/s^3]
    linear_max:
      vel : 0.5
    # 回転  速度[deg/s],加速度[deg/s^2],加減速度[-deg/s^2],躍度[deg/s^3]
    angular_max :
      vel: 30.0
    autonomous_flag : false

socketcan_interface_node:
  ros__parameters:
    if_name : "0"

chassis_driver_node:
  ros__parameters:
    wheel_radius : 0.03
    attached_direction : 0.200343
    stop_canid : 0x100
    restart_canid : 0x101
    motor_rev_canid : 0x102
    encoder_rev_canid : 0x103
    pidgain_canid : 0x104
    velocity_canid : 0x108

    motor_rev: [0, 1, 0, 0]
    encoder_rev: [0, 0, 0, 0]

    pidgain0: [0.6, 0.1, 0.0]
    pidgain1: [0.6, 0.1, 0.0]
    pidgain2: [0.6, 0.1, 0.0]
    pidgain3: [0.6, 0.1, 0.0]

pose_pid_node:
  ros__parameters:
    interval_ms : 10
    linear_pidgain : [0.0, 0.0, 0.0]
    angular_pidgain : [0.0, 0.0, 0.0]
    allowed_area : [-1.0, 1.0, -2.0, 2.0]   #[x下限，x上限，y下限，y上限]

cybergear_interface_node:
  ros__parameters:
    interval_ms : 10
    master_id : 0x00
    target_id : 0x7F

    gear_rate : 1.0
    reverse_flag : false
    # 制御対象の最小・最大位置[deg]
    pos_limit_min : -90.0
    pos_limit_max : 90.0
    # 制御対象の最大速度[deg/s] <-サイバーギアの限界速度以下に設定する
    limit_speed : 697.5 # 減速比 7.75:1

landmark_localization:
  ros__parameters:
    min_x: 0.0
    max_x: 4.0
    min_y: -0.5
    max_y: 1.0
    min_z: -0.9
    max_z: 1.0
    voxel_size_x: 0.2
    voxel_size_y: 0.2
    voxel_size_z: 0.2
    # D_voxel_size_x: 0.0015
    D_voxel_size_x: 0.05
    D_voxel_size_y: 0.05
    D_voxel_size_z: 0.05
    voxel_search_range: 2
    ball_radius: 0.1
    landmark_width: 0.9
    landmark_height: 0.91
    width_tolerance: 0.1
    height_tolerance: 0.4
    laser_weight: 10.0
    odom_weight_liner: 1.0e-2
    odom_weight_angler: 1.0e-2
    plane_iterations: 30
    line_iterations: 30
    odom2laser_x: 1.0
    odom2laser_y: 1.0
